name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.1
        uses: actions/setup-node@v3
        with:
          node-version: "18.1"
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Deploy Migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/prod/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: "${{ secrets.REGISTRY_URL }}/urlique-app:latest"
          cache-from: "type=registry,ref=${{ secrets.REGISTRY_URL }}/urlique-app:buildcache"
          cache-to: "type=registry,ref=${{ secrets.REGISTRY_URL }}/urlique-app:buildcache,mode=min"
